files_csv_header = [
    "FileID",
    "FileName",
    "author",
    "mission_title",
    "file_type",
    "file_version",
    "file_length",
    "file_size",
    "recorder",
    "source",
    "mission_date",
    "record_date",
    "latitude_reference",
    "longitude_reference",
    "object_quantity",
    "first_time_stamp",
    "final_time_stamp",
]

objects_csv_header = [
    "FileID",
    "UID",
    "TVID",
    "pilot",
    "name",
    "coalition",
    "type",
    "country",
    "launches",
    "kills",
    "killer",
    "killer_Weapon",
    "spawnTimeStamp",
    "deathTimeStamp",
    "origin",
    "launcher",
    "counter",
]

output_csv_header = [
    "FileID",
    "UID",
    "pilot",
    "name",
    "coalition",
    "type",
    "launches",
    "kills",
    "killer_name",
    "killer_Weapon_name",
    "spawnTimeStamp",
    "deathTimeStamp",
    "mission_title",
    "file_name_short",
]

output_exclude_object_types = [
    "Decoy",
    "Flare",
    "Shrapnel",
    "Weapon",
    "Projectile",
    "Shell",
    "Parachutist",
    "Building",
    "Navaid",
    "Bullseye",
    "Container",
]
